### ISSUE TITLE
This recipe book NEEDS Falafels

### ISSUE THREAD

**Issue by hhollandmoritz** [dhmsjs/recipebook#2]
Add Mom's falafel recipe.

**Comment by dhmsjs** [comment]
Surprise! I think it is already in there.  Search the master PDF doc for "Falafel #1" and you should find the one with shallots and baking powder. (Really good!)

If that is not exactly the recipe you are thinking of, then please document the differences.  Either we can add those as variations, or create a completely separate version.  Note also that there already is a "Falafel #2" recipe in the PDF as well.

And just to be clear, the "#1" and "#2" in the quoted search terms above really are parts of the recipe titles, and NOT the github tag that enumerates an issue (even though github hyperlinks them as such).

**Comment by dhmsjs** [comment]
Done!
